### ISSUE TITLE
Command specific middleware

### ISSUE THREAD

**Issue by neilcrookes** [gearhub/tactician-for-laravel#1]
Hi, thanks for this package. Just wondering does this library easily support command specific middleware, e.g. validation and authorisation etc? And if so, could you add some documentation to describe the recommended approach please?

**Comment by vsruby** [comment]
@neilcrookes No, currently there is no configuration for command specific middleware. However, you could make a middleware that looks to see if there is a validator class for a specific command. For example, you could have a command called "DoTaskCommand" and the middleware looks for a validator called "DoTaskCommandValidator" and if it found one then execute it. If it doesn't find one then just continue on to the next middleware. Let me know if this is helpful or not.

**Comment by neilcrookes** [comment]
@vsruby ok, thanks for your reply and your suggestion. It is helpful :)
